/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radiobutton2;

import java.awt.Font;

/**
 *
 * @author pawelstradomski
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSize = new javax.swing.ButtonGroup();
        malyPrzelacznik = new javax.swing.JRadioButton();
        sredniPrzelacznik = new javax.swing.JRadioButton();
        duzyPrzelacznik = new javax.swing.JRadioButton();
        etykieta = new javax.swing.JLabel();

        groupSize.add(malyPrzelacznik);
        groupSize.add(sredniPrzelacznik);
        groupSize.add(duzyPrzelacznik);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        malyPrzelacznik.setText("maly");
        malyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malyPrzelacznikActionPerformed(evt);
            }
        });

        sredniPrzelacznik.setText("sredni");
        sredniPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sredniPrzelacznikActionPerformed(evt);
            }
        });

        duzyPrzelacznik.setText("duzy");
        duzyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzyPrzelacznikActionPerformed(evt);
            }
        });

        etykieta.setText("testCzcionki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(malyPrzelacznik)
                        .addGap(3, 3, 3)
                        .addComponent(sredniPrzelacznik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duzyPrzelacznik))
                    .addComponent(etykieta))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duzyPrzelacznik, malyPrzelacznik, sredniPrzelacznik});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malyPrzelacznik)
                    .addComponent(sredniPrzelacznik)
                    .addComponent(duzyPrzelacznik))
                .addGap(18, 18, 18)
                .addComponent(etykieta)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sredniPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sredniPrzelacznikActionPerformed
        etykieta.setFont(new Font("Serif", Font.ITALIC, 25));
    }//GEN-LAST:event_sredniPrzelacznikActionPerformed

    private void malyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malyPrzelacznikActionPerformed
        etykieta.setFont(new Font("Serif", Font.CENTER_BASELINE, 15));
    }//GEN-LAST:event_malyPrzelacznikActionPerformed

    private void duzyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzyPrzelacznikActionPerformed
        etykieta.setFont(new Font("Serif", Font.ITALIC, 35));
    }//GEN-LAST:event_duzyPrzelacznikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton duzyPrzelacznik;
    private javax.swing.JLabel etykieta;
    private javax.swing.ButtonGroup groupSize;
    private javax.swing.JRadioButton malyPrzelacznik;
    private javax.swing.JRadioButton sredniPrzelacznik;
    // End of variables declaration//GEN-END:variables
}
